### ISSUE TITLE
Can't install asciiframe using cargo, "error: failed to run custom build command for `opencv v0.63.2`"

### ISSUE THREAD

**Issue by RedDragonTix** [luke-rt/asciiframe#66]
I'm trying to install asciiframe and I get this

error: failed to run custom build command for `opencv v0.63.2`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installIyRB6D/release/build/opencv-362a9923605f2d27/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=OPENCV4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SYSROOT
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rustc-cfg=ocvrs_opencv_branch_4
  cargo:rerun-if-env-changed=OPENCV_PACKAGE_NAME
  cargo:rerun-if-env-changed=OPENCV_PKGCONFIG_NAME
  cargo:rerun-if-env-changed=OPENCV_CMAKE_NAME
  cargo:rerun-if-env-changed=OPENCV_CMAKE_BIN
  cargo:rerun-if-env-changed=OPENCV_VCPKG_NAME
  cargo:rerun-if-env-changed=OPENCV_LINK_LIBS
  cargo:rerun-if-env-changed=OPENCV_LINK_PATHS
  cargo:rerun-if-env-changed=OPENCV_INCLUDE_PATHS
  cargo:rerun-if-env-changed=OPENCV_DISABLE_PROBES
  cargo:rerun-if-env-changed=CMAKE_PREFIX_PATH
  cargo:rerun-if-env-changed=OpenCV_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=VCPKG_ROOT
  cargo:rerun-if-env-changed=VCPKGRS_DYNAMIC
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/bioinspired.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/alphamat.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/videoio.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/ocvrs_common.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/sfm.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/photo.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/gapi.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/xfeatures2d.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/core.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/ccalib.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/face.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/hdf.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/dnn.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/manual-features2d.cpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/manual-dnn.cpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/aruco.hpp
  cargo:rerun-if-changed=/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/manual-core.cpp
  cargo:rerun-if-changed=Cargo.toml
  === Clang: clang version 15.0.7

  --- stderr
  === Crate version: Some("0.63.2")
  === Environment configuration:
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = None
  ===   OPENCV_LINK_PATHS = None
  ===   OPENCV_INCLUDE_PATHS = None
  ===   OPENCV_DISABLE_PROBES = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = None
  ===   PKG_CONFIG_PATH = None
  ===   VCPKG_ROOT = None
  ===   VCPKGRS_DYNAMIC = None
  === Enabled features:
  ===   ALPHAMAT
  ===   ARUCO
  ===   BARCODE
  ===   BGSEGM
  ===   BIOINSPIRED
  ===   CALIB3D
  ===   CCALIB
  ===   CUDAARITHM
  ===   CUDABGSEGM
  ===   CUDACODEC
  ===   CUDAFEATURES2D
  ===   CUDAFILTERS
  ===   CUDAIMGPROC
  ===   CUDAOBJDETECT
  ===   CUDAOPTFLOW
  ===   CUDASTEREO
  ===   CUDAWARPING
  ===   CVV
  ===   DEFAULT
  ===   DNN
  ===   DNN_SUPERRES
  ===   DPM
  ===   FACE
  ===   FEATURES2D
  ===   FLANN
  ===   FREETYPE
  ===   FUZZY
  ===   GAPI
  ===   HDF
  ===   HFS
  ===   HIGHGUI
  ===   IMGCODECS
  ===   IMGPROC
  ===   IMG_HASH
  ===   INTENSITY_TRANSFORM
  ===   LINE_DESCRIPTOR
  ===   MCC
  ===   ML
  ===   OBJDETECT
  ===   OPTFLOW
  ===   OVIS
  ===   PHASE_UNWRAPPING
  ===   PHOTO
  ===   PLOT
  ===   QUALITY
  ===   RAPID
  ===   RGBD
  ===   SALIENCY
  ===   SFM
  ===   SHAPE
  ===   STEREO
  ===   STITCHING
  ===   STRUCTURED_LIGHT
  ===   SUPERRES
  ===   SURFACE_MATCHING
  ===   TEXT
  ===   TRACKING
  ===   VIDEO
  ===   VIDEOIO
  ===   VIDEOSTAB
  ===   VIZ
  ===   WECHAT_QRCODE
  ===   XFEATURES2D
  ===   XIMGPROC
  ===   XOBJDETECT
  ===   XPHOTO
  === Detected probe priority based on environment vars: pkg_config: false, cmake: false, vcpkg: false
  === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
  === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
  === Probing OpenCV library using pkg_config
  === OpenCV library configuration: Library {
      include_paths: [
          "/usr/include/opencv4",
      ],
      version: Version {
          major: 4,
          minor: 8,
          patch: 0,
      },
      cargo_metadata: [
          "cargo:rustc-link-search=/usr/lib",
          "cargo:rustc-link-lib=opencv_gapi",
          "cargo:rustc-link-lib=opencv_stitching",
          "cargo:rustc-link-lib=opencv_alphamat",
          "cargo:rustc-link-lib=opencv_aruco",
          "cargo:rustc-link-lib=opencv_bgsegm",
          "cargo:rustc-link-lib=opencv_bioinspired",
          "cargo:rustc-link-lib=opencv_ccalib",
          "cargo:rustc-link-lib=opencv_cvv",
          "cargo:rustc-link-lib=opencv_dnn_objdetect",
          "cargo:rustc-link-lib=opencv_dnn_superres",
          "cargo:rustc-link-lib=opencv_dpm",
          "cargo:rustc-link-lib=opencv_face",
          "cargo:rustc-link-lib=opencv_freetype",
          "cargo:rustc-link-lib=opencv_fuzzy",
          "cargo:rustc-link-lib=opencv_hdf",
          "cargo:rustc-link-lib=opencv_hfs",
          "cargo:rustc-link-lib=opencv_img_hash",
          "cargo:rustc-link-lib=opencv_intensity_transform",
          "cargo:rustc-link-lib=opencv_line_descriptor",
          "cargo:rustc-link-lib=opencv_mcc",
          "cargo:rustc-link-lib=opencv_quality",
          "cargo:rustc-link-lib=opencv_rapid",
          "cargo:rustc-link-lib=opencv_reg",
          "cargo:rustc-link-lib=opencv_rgbd",
          "cargo:rustc-link-lib=opencv_saliency",
          "cargo:rustc-link-lib=opencv_stereo",
          "cargo:rustc-link-lib=opencv_structured_light",
          "cargo:rustc-link-lib=opencv_phase_unwrapping",
          "cargo:rustc-link-lib=opencv_superres",
          "cargo:rustc-link-lib=opencv_optflow",
          "cargo:rustc-link-lib=opencv_surface_matching",
          "cargo:rustc-link-lib=opencv_tracking",
          "cargo:rustc-link-lib=opencv_highgui",
          "cargo:rustc-link-lib=opencv_datasets",
          "cargo:rustc-link-lib=opencv_text",
          "cargo:rustc-link-lib=opencv_plot",
          "cargo:rustc-link-lib=opencv_videostab",
          "cargo:rustc-link-lib=opencv_videoio",
          "cargo:rustc-link-lib=opencv_viz",
          "cargo:rustc-link-lib=opencv_wechat_qrcode",
          "cargo:rustc-link-lib=opencv_xfeatures2d",
          "cargo:rustc-link-lib=opencv_shape",
          "cargo:rustc-link-lib=opencv_ml",
          "cargo:rustc-link-lib=opencv_ximgproc",
          "cargo:rustc-link-lib=opencv_video",
          "cargo:rustc-link-lib=opencv_xobjdetect",
          "cargo:rustc-link-lib=opencv_objdetect",
          "cargo:rustc-link-lib=opencv_calib3d",
          "cargo:rustc-link-lib=opencv_imgcodecs",
          "cargo:rustc-link-lib=opencv_features2d",
          "cargo:rustc-link-lib=opencv_dnn",
          "cargo:rustc-link-lib=opencv_flann",
          "cargo:rustc-link-lib=opencv_xphoto",
          "cargo:rustc-link-lib=opencv_photo",
          "cargo:rustc-link-lib=opencv_imgproc",
          "cargo:rustc-link-lib=opencv_core",
      ],
  }
  === Detected OpenCV module header dir at: /usr/include/opencv4/opencv2
  === Found OpenCV version: 4.8.0 in headers located at: /usr/include/opencv4
  === Generating code in: /tmp/cargo-installIyRB6D/release/build/opencv-e377505dd4c8746f/out
  === Placing generated bindings into: /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src/opencv
  === Using OpenCV headers from: /usr/include/opencv4
  === Clang command line args: [
      "-isystem/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1",
      "-isystem/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu",
      "-isystem/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward",
      "-isystem/usr/lib/clang/15.0.7/include",
      "-isystem/usr/local/include",
      "-isystem/usr/include",
      "-I/usr/include/opencv4",
      "-F/usr/include/opencv4",
      "-I/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp",
      "-F/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp",
      "-DOCVRS_PARSING_HEADERS",
      "-includeocvrs_ephemeral.hpp",
      "-std=c++14",
  ]
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/alphamat.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/calib3d.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/dnn_superres.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/aruco.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/dnn.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/face.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/bgsegm.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/bioinspired.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/core.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/ccalib.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/cvv.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/fuzzy.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/hfs.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/dpm.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/freetype.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/features2d.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/flann.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/highgui.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/img_hash.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/hdf.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/intensity_transform.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/imgproc.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/imgcodecs.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/ml.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/line_descriptor.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/objdetect.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/plot.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/optflow.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/quality.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/src_cpp/photo.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/mcc.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/rapid.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/phase_unwrapping.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/rgbd.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/saliency.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/shape.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/stereo.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/superres.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/structured_light.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread '<unnamed>' panicked at 'internal error: entered unreachable code: Can't get kind of parent for cpp namespace: Entity {
      kind: NotImplemented,
      display_name: Some(
          "/usr/include/opencv4/opencv2/surface_matching.hpp",
      ),
      location: None,
  }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-binding-generator-0.41.0/src/element.rs:75:21
  thread 'main' panicked at 'Generator thread panicked: Any { .. }', /home/demax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opencv-0.63.2/build/generator.rs:149:28
error: failed to compile `asciiframe v1.2.0`, intermediate artifacts can be found at `/tmp/cargo-installIyRB6D`

**Comment by luke-rt** [comment]
Working on this right now

**Comment by luke-rt** [comment]
- `brew install pkg-config opencv`
- If you get `dyld: Library not loaded: @rpath/libclang.dylib` then run `export DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/usr/lib/"` first
